language: go

go:
  - "1.10.x"

before_install:
  - go get -t github.com/Masterminds/glide
  - go get -t github.com/codeclimate/test-reporter
  - glide install
  
before_script:
  - test-reporter before-build

script:
  - go test -coverprofile c.out ./...

after_script:
  - test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
